# Step 1: Understanding Text Noise

In [1]:
import pandas as pd
import numpy as np

import re
import string

import nltk
import spacy

from nltk.corpus import stopwords

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv(
    "../data/processed/imdb_cleaned.csv"
)

print(df.shape)

(49582, 2)

In [3]:
df["review"].sample(5).values

<ArrowStringArray>
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'With so many good movies coming out in 1995 (particularly "Mortal Kombat" and "Seven"), unfortunately, there had to be some bombs as well, and this film indeed falls into the latter category with a boring, predictable plot and a lousy ending. It seems that Antonio Banderas hasn't been able to find a decent script since "Desperado," the only remarkable film he's done. Anyone with an eighth of a brain could tell who DeMornay's stalker was from the beginning. Her flashbacks of the death of her mother did nothing but muddle an already paper-thin story. Pity that Dennis Miller was wasted in this film; this part resembles his eerily similar role in "The Net." <br /><br />The convoluted ending had me shaking my head, as I pretty much did throughout the entire movie. Plus, any film that depicts animal cruelty in any shape or form, no matter how fake it looks, automatically gets the thumbs-down from me. <br /><br />To make a long story short, if you want to enjoy a good thriller, then avoid this at all costs. Never talk to strangers...especially those who recommend this movie. 2/10',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 '"Opposing Force [1986]" wasn't as good as "Dr. Strangelove" and it wasn't as good as "The Bridge on the River Kwai". Heck, it wasn't even as good as "G.I. Jane", which is pretty sad.<br /><br />The film revolves around a basic ethical problem: In a simulated prisoner-of-war situation, how far can you go before you start breaking the law? What exactly IS the law in such a situation? How can you simulate the torture of someone without actually torturing someone? Can you intentionally inflict pain? How about breaking bones? Mock executions? Sexual abuse? Severe blood loss? Real guns with bullets? Death? Somewhere between these is a really fuzzy line dividing "acceptable" from "atrocious".<br /><br />Now, what could you do if you found yourself in such a training program and the lines between simulation and reality begin to vanish? What could you do? This movie attempts to portray this dilemma.<br /><br />I found it interesting to see the types of tactics used in "resistance training". I have a brother who went through the USAF's POW training program. According to him, it was pretty close to the mark technically.<br /><br />The film has a fairly good premise, but it doesn't have a particularly good story. I wondered if it might be based on some actual event, but it became pretty apparent that it wasn't when the explosions started. They must have changed scriptwriters three quarters into the film, because it takes a real extreme turn and devolves into a somewhat pointless shoot-em-up with lots of distracting explosions. <br /><br />I found it to have a rather unsatisfying ending; again, kind of pointless. I'm left wondering what the point of the whole thing was - I'm beginning to suspect there simply wasn't one. It could have been much better with just a little more story to go along with the fireworks.',
 'Watching "Ossessione" today -- more than 6 decades later -- is still a powerful experience, especially for those interested in movie history and more specifically on how Italian filmmakers changed movies forever (roughly from "Ossessione" and De Sica's "I Bambini Ci Guardano", both 1943, up to 20 years later with Fellini, Antonioni, Pasolini). Visconti makes an amazing directing début, taking the (uncredited) plot of "The Postman Always Rings Twice" as a guide to the development of his own themes.<br /><br />It strikes us even today how ahead of its time "Ossessione" was. Shot in Fascist Italy during World War II (think about it!!), it depicted scenes and themes that caused the film to be immediately banned from theaters -- and the fact that it used the plot of a famous American novel and payed no copyright didn't help. <br /><br />"Ossessione" alarmingly reveals poverty-ridden war-time Italy (far from the idealized Italy depicted in Fascist "Telefoni Bianchi" movies); but it's also extremely daring in its sexual frankness, with shirtless hunk Gino (Massimo Girotti, who definitely precedes Brando's Kowalski in "A Streetcar Named Desire") taking Giovanna (Clara Calamai), a married woman, to bed just 5 minutes after they first meet. We watch Calamai's unglamorous, matter-of-fact undressing and the subtle but undeniable homosexual hints between Gino and Lo Spagnolo (Elio Marcuzzo - a very appealing actor, his face not unlike Pierre Clémenti's, who was shot by the Nazis in 1945, at 28 years old!)...In a few words: sex, lust, greed and poverty, as relentlessly as it had rarely, if ever, been shown before in Italian cinema.<br /><br />All the copies of "Ossessione" were destroyed soon after its opening -- it was called scandalous and immoral. Visconti managed to save a print, and when the film was re-released after the war, most critics called it the front-runner of the Neo-Realist movement, preceding Rossellini's "Roma CIttà Aperta" and De Sica's "Sciuscià". Some other critics, perhaps more appropriately, saw "Ossessione" as the Italian counterpart to the "poetic realism" of French cinema (remember Visconti had been Renoir's assistant), especially Marcel Carné's "Quai des Brumes" and "Le Jour se Lève", and Julien Duvivier's "Pépé le Moko". <br /><br />While "Ossessione" may be Neo-Realistic in its visual language (the depiction of war-time paesan life in Italy with its popular fairs, poverty, child labor, prostitution, bums, swindlers etc), the characters and the themes were already decidedly Viscontian. He was always more interested in tragic, passionate, obsessive, greedy characters, in social/political/sexual apartheid, in the decadence of the elites than in realistic, "everyday- life" characters and themes, favored by DeSica and Rossellini. In "Ossessione" we already find elements of drama and tragedy later developed in many of his films, especially "Senso" (Visconti's definitive departure from Neo-Realist aesthetics) and "Rocco e Suoi Fratelli"...Even in his most "Neo-Realist" film, "La Terra Trema", he makes his fishermen rise from day-to-day characters to mythological figures.<br /><br />"Ossessione" is a good opportunity to confirm the theory about great artists whose body of work approaches, analyzes and develops specific themes and concerns over and over again, from their first to their last opus, no matter if the scenery, background or time-setting may change -- Visconti may play with the frame but the themes and essence of his art are, well, obsessively recurrent. "Ossessione" is not to be missed: you'll surely be fascinated by this ground-breaking, powerful film.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'Jack Frost returns with an army of Styrofoam balls that can only be foiled by being shot with super-soakers loaded with margaritas. How's that for a plot? The film hinges on such a ridiculous premise that it barely raises an eyebrow when characters are killed with BBQ tongs and are impaled by carrots. You might even say the whole movie is skating on thin ice (ba-boom-tish).<br /><br />Admittedly, there are some fantastic one-liners including a remark about the Murderous Coconut Shark.<br /><br />Fair enough times are hard, but that does not excuse the willingness of the actors to take part in such utter tripe.<br /><br />For those fans hoping to see Jack Frost, be prepared to accept him as merely a phallic carrot creeping up the beach with corny voice-over commentary.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'In a way this is the disaster Fellini has been working towards all his life. The line between absurd masterpiece and free association bullshit is very small, and what category a film will ultimately fit in will often just depend on personal feelings. That said, "Casanova" left me in cold admiration for its sets and little more that cannot be summed up more adequately by Bukowski: <br /><br />"Casanova died too, just an old guy with a big cock and a long tongue and no guts at all. to say that he lived well is true; to say I could spit on his grave without feeling is also true. the ladies usually go for the biggest fool they can find; that is why the human race stands where it does today: we have bred the clever and lasting Casanovas, all hollow inside, like the Easter bunnies we foster upon our poor children." <br /><br />As far as I could make it out, this is the position Fellini takes regarding his subject; granted, with more empathy, but disgusted nonetheless.<br /><br />Casanova's environment is made from decay and incestuous behavior, themes Fellini dealt with more pointedly in "Satyricon". The succession of plot is characteristic of soft porn, just without the coherence; and Donald Sutherland is ugly and slimy to the point of distraction.<br /><br />Yet, there might just be a point in portraying Casanova as an unsightly fool. And I challenge anybody to formulate this point without being obvious; Fellini couldn't. More than ever he seems here like a dirty old man - a maestro, for sure, but one whose impulses satisfy himself more than anybody else. I find it hard imagine an audience who enjoys this film. It was a story not worth telling.']
Length: 5, dtype: str

In [4]:
sample_review = df["review"][0]

print(sample_review)

One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.

# Step 2: Lowercasing

In [5]:
df["clean_review"] = df["review"]

In [6]:
df[["review", "clean_review"]].head()

,review,clean_review
0,One of the other reviewers has mentioned that ...,One of the other reviewers has mentioned that ...
1,A wonderful little production. <br /><br />The...,A wonderful little production. <br /><br />The...
2,I thought this was a wonderful way to spend ti...,I thought this was a wonderful way to spend ti...
3,Basically there's a family where a little boy ...,Basically there's a family where a little boy ...
4,"Petter Mattei's ""Love in the Time of Money"" is...","Petter Mattei's ""Love in the Time of Money"" is..."

# review         → Original Data (Never Touch)
# clean_review   → Working Copy (Apply Cleaning)

In [7]:
df["clean_review"] = df["clean_review"].str.lower()

In [8]:
print(df["review"][0][:200])

One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me abo

In [9]:
print(df["clean_review"][0][:200])

one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.<br /><br />the first thing that struck me abo

# Step 2 Findings

### Lowercasing

Text was converted to lowercase to ensure consistency.

Examples:

Movie → movie

MOVIE → movie

movie → movie

This reduces vocabulary size and improves model performance.

# Step 3: Remove HTML Tags

In [10]:
from bs4 import BeautifulSoup

In [11]:
def remove_html_tags(text):
    return BeautifulSoup(text, "html.parser").get_text()

In [12]:
df["clean_review"] = df["clean_review"].apply(
    remove_html_tags
)

In [13]:
print(df["review"][0][:300])

One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Tru

In [14]:
print(df["clean_review"][0][:300])

one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this

# Step 3 Findings

### HTML Tag Removal

HTML tags such as:

- <br />
- <br /><br />

were removed successfully.

These tags do not contribute to sentiment and are considered textual noise.

### Conclusion

The review text is now cleaner and more suitable for NLP processing.

In [15]:
df["clean_review"].str.contains(
    "http|www",
    case=False,
    regex=True
).sum()

np.int64(243)

# Step 4 – URL Removal

In [16]:
url_reviews = df[
    df["clean_review"].str.contains(
        "http|www",
        case=False,
        regex=True
    )
]

url_reviews["clean_review"].head(5).values

<ArrowStringArray>
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   'first of all, let's get a few things straight here: a) i am an anime fan- always has been as a matter of fact (i used to watch speed racer all the time in preschool). b) i do like several b-movies because they're hilarious. c) i like the godzilla movies- a lot.moving on, when the movie first comes on, it seems like it's going to be your usual b-movie, down to the crappy fx, but all a sudden- boom! the anime comes on! this is when the movie goes wwwaaaaayyyyy downhill.the animation is very bad & cheap, even worse than what i remember from speed racer, for crissakes! in fact, it's so cheap, one of the few scenes from the movie i "vividly" remember is when a bunch of kids run out of a school... & it's the same kids over & over again! the fx are terrible, too; the dinosaurs look worse than godzilla. in addition, the transition to live action to animation is unorganized, the dialogue & voices(especially the english dub that i viewed) was horrid & i was begging my dad to take the tape out of the dvd/ vhs player; the only thing that kept me surviving was cracking out jokes & comments like the robots & joel/mike on mst3k (you pick the season). honestly, this is the only way to barely enjoy this movie & survive it at the same time.heck, i'm planning to show this to another fellow otaku pal of mine on halloween for a b-movie night. because it's stupid, pretty painful to watch & unintentionally hilarious at the same time, i'm giving this movie a 3/10, an improvement from the 0.5/10 i was originally going to give it.(according to my grading scale: 3/10 means pretty much both boring & bad. as fun as counting to three unless you find a way to make fun of it, then it will become as fun as counting to 15.)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           'awwww, i just love this movie to bits. me and my cousins enjoy this movie a lot and i am just such a huge fan!!! i hope they bring the tv series out on dvd soon. come to mention it, i have not see the tv show in a long time. such geart times! where i come from australia the chipmunk adventure is only known by people in their late teens and adult years which is kinda sad because the young kids don't know what there missing.the songs in this film are ace the ones i love the most boys/girls of rock n'roll, diamond dolls and the song that ls sure to make you want to cry my mother.this film is sure to excite both young and old get the chipmunk adventure today!!! 10 out of 10, such an excellent movie.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          'mario lewis of the competitive enterprise institute has written a definitive 120-page point-by-point, line-by-line refutation of this mendacious film, which should be titled a convenient lie. the website address where his debunking report, which is titled "a skeptic's guide to an inconvenient truth" can be found at is :www.cei.org. a shorter 10-page version can be found at: www.cei.org/pdf/5539.pdf once you read those demolitions, you'll realize that alleged "global warming" is no more real or dangerous than the y2k scare of 1999, which gore also endorsed, as he did the pseudo-scientific film the day after tomorrow, which was based on a book written by alleged ufo abductee whitley strieber. as james "the amazing" randi does to psychics, and philip klass does to ufos, and gerald posner does to jfk conspir-idiocy theories, so does mario lewis does to al gore's movie and the whole "global warming" scam.',
 'following directly from where the story left off in part one, the second half which sets about telling the inevitable downfall and much more grim side of the man's legacy is exactly as such. in direct contrast to the first feature, part two represents a shift from che the pride and glory of a revolutionised country, to chestruggling liberator of a country to which he has no previous ties. the change of setting isn't just aesthetic; from the autumn and spring greys of the woodlands comes a change of tone and heart to the feature, replacing the optimism of the predecessor with a cynical, battered and bruised reality aligned to an all new struggle. yet, as che would go on to say himselfsuch a struggle is best told exactly as thata struggle. while part one certainly helped document that initial surge to power that the revolutionary guerrilla acquired through just that, part two takes a much more refined, callous and bleak segment of che's life and ambition, and gives it an assertive portrayal that is both poignant and tragic in a tangible, easy to grasp manner.while the movie's tone in some regards does stray off and differ quite drastically from part one however, there still remains that same documented approach taken a month ago that avoids melodrama and fabrication as much as possible. this somewhat distant, cold approach to telling che's story and struggle will no doubt turn some viewers off; indeed, i still remain reserved about whether or not the feature itself should have been named after one manif anything, the entirety of che, taken as a whole, delivers a tale that goes beyond mere biography and instead documents a man's struggle alongside those who helped carry him along the way. by no means does soderbergh try to paint a humanistic portrait here akin to what hirschbiegel did with der untergang half a decade ago (excuse the ironic contrast); che is a slow moving, reserved and meditative approach to telling a history lesson that just happens to be narrated by the one man who arguably- conducted the whole thing.yet by moving from the lush green landscapes of cuba and retreating to the bleak, decaying backdrop of bolivia for part two, the story does inevitably take on a distinctly contrasting tone that doesn't feel too disjointed from its predecessor, but does enough to give it its own reference points. here, the basic structure of part one is echoed backthere's the initial struggle, the battles, the fallen comrades and the recruiting of those to replace them, all the while we see some glimpses of the man behind the movement. yet, as anyone with the vaguest idea of the actual history behind the feature will know, part two is destined to end on a much more underwhelming, and disquieting note. this difference, in combination with the similarities to part one, make a compelling and memorable whole; by all means, both could be digested one their own (and kudos to soderbergh for achieving as such) and enjoyed as they are, but taken as one statement, che delivers exactly what it sets out to achieve.indeed, everything that made part one the treat that it was one month prior is still evident here from the subtle yet engrossing performances from the central cast to the slow building, realistically structured combat scenesthe drama inherent to the characters on screen is just as vague and indiscernible, but with a feature such as this, part two once again proves that avoiding such elements don't necessarily hurt a film when there is enough plot and reflection on other elements to keep the viewer engaged. in fact, upon writing this review i was at odds as to whether or not to simply add a paragraph or two to my initial review for part one, and title the review as a whole, yet i felt that to do so would only serve to disillusion those who may sit down to watch the entirety of both films consecutively.with that said, i cannot rightfully decree whether or not che holds up to the task of engaging an audience for its sprawling four hour plus runtime, but upon viewing both segments i can at least attest to each part's ability to do just that. with a reflective, intricate screenplay combined with endlessly mesmerising photography and nuanced performances that do justice to the movie's characters without drawing attention to themselves, che part two is every bit as compelling and rewarding as its predecessor, but this time with a tragic but uplifting, reaffirming conclusion fit for the history pages of film.- a review by jamie robert ward (http://www.invocus.net)',

# Step 4: URL Removal

URLs are considered noise for sentiment analysis.

We remove them because they usually do not contribute to determining sentiment.

In [17]:
def remove_urls(text):
    pattern = r'https?://\S+|www\.\S+'
    return re.sub(pattern, '', text)

In [18]:
df["clean_review"] = df["clean_review"].apply(
    remove_urls
)

In [19]:
df["clean_review"].str.contains(
    "http|www",
    case=False,
    regex=True
).sum()

np.int64(50)

In [20]:
pattern = r'https?://\S+|www\.\S+'

In [21]:
remaining_urls = df[
    df["clean_review"].str.contains(
        "http|www",
        case=False,
        regex=True
    )
]

remaining_urls["clean_review"].head(10).tolist()

['first of all, let\'s get a few things straight here: a) i am an anime fan- always has been as a matter of fact (i used to watch speed racer all the time in preschool). b) i do like several b-movies because they\'re hilarious. c) i like the godzilla movies- a lot.moving on, when the movie first comes on, it seems like it\'s going to be your usual b-movie, down to the crappy fx, but all a sudden- boom! the anime comes on! this is when the movie goes wwwaaaaayyyyy downhill.the animation is very bad & cheap, even worse than what i remember from speed racer, for crissakes! in fact, it\'s so cheap, one of the few scenes from the movie i "vividly" remember is when a bunch of kids run out of a school... & it\'s the same kids over & over again! the fx are terrible, too; the dinosaurs look worse than godzilla. in addition, the transition to live action to animation is unorganized, the dialogue & voices(especially the english dub that i viewed) was horrid & i was begging my dad to take the tape out of the dvd/ vhs player; the only thing that kept me surviving was cracking out jokes & comments like the robots & joel/mike on mst3k (you pick the season). honestly, this is the only way to barely enjoy this movie & survive it at the same time.heck, i\'m planning to show this to another fellow otaku pal of mine on halloween for a b-movie night. because it\'s stupid, pretty painful to watch & unintentionally hilarious at the same time, i\'m giving this movie a 3/10, an improvement from the 0.5/10 i was originally going to give it.(according to my grading scale: 3/10 means pretty much both boring & bad. as fun as counting to three unless you find a way to make fun of it, then it will become as fun as counting to 15.)',
 "awwww, i just love this movie to bits. me and my cousins enjoy this movie a lot and i am just such a huge fan!!! i hope they bring the tv series out on dvd soon. come to mention it, i have not see the tv show in a long time. such geart times! where i come from australia the chipmunk adventure is only known by people in their late teens and adult years which is kinda sad because the young kids don't know what there missing.the songs in this film are ace the ones i love the most boys/girls of rock n'roll, diamond dolls and the song that ls sure to make you want to cry my mother.this film is sure to excite both young and old get the chipmunk adventure today!!! 10 out of 10, such an excellent movie.",
 'possible spoilers, perhaps. i must say that "cinderella ii: dreams come true" is one of the worst movies ever made. first of all, the movie was made during the height of disney\'s sequel rampage. it was created around the same time as "the little mermaid ii," "the jungle book ii," and "peter pan ii," all of which were disservices to their original film classics. (disney also made "the hunchback of notre dame ii" and "atlantis ii," but i\'m going to drop that topic because their original movies were never really classics in the first place.") let me go ahead and say that i am an avid supporter of good disney films, and i absolutely adore the original disney "cinderella." the sequel to "cinderella," however, was a waste of time. the character of cinderella in the sequel was so very unlike the original girl that i grew up watching. in the original, cinderella was kind and loving. the new cinderella had very out-of-character moments with current-era phrasing like, "i\'m going to do this banquet my way!" let me also tell you that new cinderella (as i have affectionately named her) says, "ewww!" that is the anti-cinderella. i try to find the best in people, but in the sequel, anastasia, one of the stepsisters, is good! what the heck? why? they made it all out to be like lady tremaine and drizella are just horrible family members for poor little anastasia. my question to the world: did the people at disney watch the original "cinderella" when making this sequel? well, it surely doesn\'t seem so. if i remember correctly, anastasia was just as abusive to cinderella as drizella and lady tremaine. i am all for redemption and forgiveness, but there was no point of redemption for anastasia in this movie. in the first one, anastasia was evil. in the second one, she is good. one just can\'t leave a story like this. i hope disney realizes that this movie, among other movies, is shaming walt disney\'s name. perhaps now that michael eisner is gone, things will start shaping up around the house of mouse.',
 "i have just recently purchased collection one of this awesome series and even after just watching three episodes, i still am mesmerized by sleek styling of the animation and the slow, yet thoughtful actions of the story-telling. i am still a fan.....with some minor pains.though this installment into the gundam saga is very cool and has what the previous series had-a stylish satiric way of telling about the wrongs of war and not letting go of the need to have control or power over everything(sound familiar?), i have to say that this one gets a bit too mellow-dramatic on continuing to explain the lives of the main characters and their incessant need to belly-ache about every thing that happens and what they need to do to stop the oz group from succeeding in their plans(especially the character called wufei...i mean he whines more than an american character on a soap opera. get a counselor,will ya?)besides for the over-exaggerated drama(i think that mostly comes from the dubbing of the english voice actors), this series is still very exciting and will still captivate me once again. i mean it can always be worse. it could be like the recent installment, seed......eeeewwww, talk about mellow-dramatic....i'll chat about that one later.",
 'it is finally coming out. the first season will be available march 2007. it is currently airing on abc family from 4-5 pm eastern time monday through friday. the last episode will air on december 19th at 4:30. i missed it the first 100 times around. i wish i could buy the whole series right now. who does she pick? i have to write 10 lines in order to reply to the first comment. what am i going to say. la da da de de. la da da de de nope only up to 8 how do i get to 9 almost almost awww 9 now i need 10 - 1, 2, 3, 4, 5, 6, 7, i missed counted this is only number 8. punky brewster is pretty awesome too. almost to 10 almost awwwwww.',
 "ok, to start with, this movie was not at all like the book. i read the book when i was 13 and since then it has always been my favorite. when i'm waiting for a different book to come out, this is the book i turn to to fill in the time. i have 3 copies for god's sake. anyways, i knew this was not going to be anything like the book but come on! they could have done a little better than this. i mean seriously if i wanted to watch american werewolf in paris or london than i would watch those movies. they took a perfectly good story and twisted it around into a copy of a story that has been told over and over again and quite frankly i'm tired of watching it. i mean hello the best part of the whole f*****g (sorry) story is she ends up with gabriel. he doesn't die. what was that about? and he's old in this movie. gabriel is supposed to be only 24 not 44 da** it. awww. and astrid who the he** came up with the idea of astrid being vivian's aunt no no no no. astrid and vivian hate each other. awwww. anyways yeah that was my little rant seriously pi**ed off. hope this helped.",
 'well to answer one persons\'s question of "why doesn\'t anyone remember this film?" it\'s because really,not that many people saw it in 1978 and it\'s not been shown much on tv since. (if it\'s on video that\'d be news to me!) even in the era of sometimes mindless comedies that was the \'70s,movie-goers had the smarts to avoid this film. unless they love billy crytal,paul lynde or joan rivers "that" much! paul lynde was funnier on "bewitched" or "hollywood squares" than here. joan rivers at this time in her career was getting laughs making cruel jokes about singer karen carpenter\'s lack of weight! har-har joan! it also seems like every "somewhat" famous name from the era is in the cast. (most surprising is doris roberts later of "everybody loves raymond".)anyhow,a somewhat good idea for a storyline,a man getting pregnant instead of the woman goes to waste here. with help from a male friend crystal gets set up with a hooker to finally lose his virginity but because she was "on top" instead of him,he gets pregnant! (a commentary on women taking positions of power away from men).crystal\'s stomach grows,he goes through all the female emotions and related feelings. unfortunately,he is now a socially misunderstood outcast! he\'s attacked by a mob who wants him rubbed out (i guess).he\'s forced to go into seclusion to have his baby...in a barn. or if you will,a manger (god only knows where it may have exited from! ewwww!) it turns out (no shock here) to be a girl! everything else about this movie is worthless and forgettable,the humor is high school level or less.2 stars for a good idea and a few good touching & relevant moments w/ billy crystal. ignore the rest of rabitt test,it flunks big time!i can\'t believe roddy mcdowell signed on either! (end)',
 'the frozen limits is a big screen vehicle for the artists known as the crazy gang. they were a group of british entertainers who formed in the early 1930s. in the main the group\'s six men were bud flanagan, chesney allen, jimmy nervo, teddy knox, charlie naughton and jimmy gold. hugely popular in the variety halls the group were also darlings of the then royal family. the plot here sees them as the wonder boys troupe who set off to seek their fortunes in alaska after reading about a gold rush in the newspaper. only problem is is that when they finally get to red gulch it turns out they are 40 years too late!i often cringe when i see the statement "it\'s very british" because it implies that those not of the british isles may struggle to get it. the reason it bothers me is because in this www/internet age i have garnered a ream of non british film loving friends who have been known to split their sides at the best of ealing, will hay and the imperious terry-thomas. so, then, is it true that something such as the frozen limits is unlikely to be appreciated by a non british audience? well yes it\'s true, so much here is topically british, but really it has to be said that the classic movie fan is pretty well versed in history, and when all is said and done the visual mirth here is universal. with the anarchic "not" so wild west make over an absolute winner. a winner that has every chance of being more appreciated by an american audience now than it will be by a british audience. not all the comedy works, and in truth the "big 6" are trumped big time by a film stealing moore marriott. but there are skits and parodies here that deserve respect and a nod of approval from more illustrious comedy acts. you are unlikely to nearly fall off your chair like i did because of an ovaltine gag, but if you be a classic comedy film fan? i feel sure that you will at the worst acknowledge there\'s some very talented people at work here.now then, dose the mounties always get their man? 8/10',
 'think you\'ve seen the worst movie in the world? think again. the person who designed the cover of this box should be accused of false advertising. the cover makes it look like a good, scary horror suspense thriller. but, no. what we have instead is nightscream. a movie that makes a "sweeeoooowww!!" noise every time a credit flashes across the screen. the biggest name in the entire film is probably casper van dien who hardly has a part.i voted a one for this one only because i couldn\'t vote any lower. if i could vote something like negative five-thousand, trust me, i would have. so, for now, i\'m going to give nightscream 1/2* out of 5 just because it ended.',
 "feh. this movie started out in an interesting manner, but quickly ran the gamut from confusing to dull. the confusing parts happened mostly at the beginning, where the cut scenes are so numerous that its hard to tell just what is going on for the first twenty minutes or so. the dull comes later, with a tepid romance between the two living people(pusses both). the vengeful spirit of the dead girl is actually the most lively person in the film, which is sad. if the rest of the cast had been up to her caliber, the movie might have been better.maybe. because the storyline gets really interesting for awhile, as it appears that the insane priestess mother of the dead sixteen year old girl is trying to resurrect her daughter from the dead, with the decidedly unfortunate side effect that all of the other dead people would come back as well, take on solid human form, and most likely start killing off everybody. a sort of japanese mystical night of the living dead type thing. but this doesn't come to pass. even though this hairy unwashed priest with a tiny basket strapped to his head tells the uninteresting young people that this will come to pass if the priestess finishes her ritual, she does just that and the only dead person who manifests is her daughter. no mass rising of the dead, no walking army of corpses, nothing. the priest merely makes the girl's spirit go back to the land of the dead, taking the washed out wuss of a boyfriend with her, as she'd crushed his spine like peanut brittle(at which point i was tempted to cheer loudly, as this idiot went over to kiss and fondle the dead girl,,ewwww!!!). the robitussen sucking, spineless best friend has a long introspective shot at the end as she leaves the village for the last time, and that's it. no real horror, no real creepiness, which the japanese tend to do far better than american film makers with their emphasis on over-the-top cheesy face make-up, no screaming mimis. i was very disappointed."]

In [22]:
df[
    df["clean_review"].str.contains(
        r'https?://|www\.',
        case=False,
        regex=True
    )
]

,review,sentiment,clean_review
3534,It is finally coming out. The first season wil...,positive,it is finally coming out. the first season wil...
3940,"OK, to start with, this movie was not at all l...",negative,"ok, to start with, this movie was not at all l..."
11223,"Seriously, all these Satan comes to Earth movi...",negative,"seriously, all these satan comes to earth movi..."
11282,I can't believe I'm wasting my time with a com...,negative,i can't believe i'm wasting my time with a com...
19423,POSSIBLE SPOILERS --<br /><br />I love Dennis ...,negative,possible spoilers --i love dennis quaid and i ...
30411,"It's a kinder, gentler Cyborg movie with a lov...",negative,"it's a kinder, gentler cyborg movie with a lov..."
40931,"I really wanted to like this movie, but it was...",negative,"i really wanted to like this movie, but it was..."

In [25]:
remaining_urls = df[
    df["clean_review"].str.contains(
        r'https?://|www\.',
        case=False,
        regex=True
    )
]

remaining_urls["clean_review"].head(10).tolist()

['it is finally coming out. the first season will be available march 2007. it is currently airing on abc family from 4-5 pm eastern time monday through friday. the last episode will air on december 19th at 4:30. i missed it the first 100 times around. i wish i could buy the whole series right now. who does she pick? i have to write 10 lines in order to reply to the first comment. what am i going to say. la da da de de. la da da de de nope only up to 8 how do i get to 9 almost almost awww 9 now i need 10 - 1, 2, 3, 4, 5, 6, 7, i missed counted this is only number 8. punky brewster is pretty awesome too. almost to 10 almost awwwwww.',
 "ok, to start with, this movie was not at all like the book. i read the book when i was 13 and since then it has always been my favorite. when i'm waiting for a different book to come out, this is the book i turn to to fill in the time. i have 3 copies for god's sake. anyways, i knew this was not going to be anything like the book but come on! they could have done a little better than this. i mean seriously if i wanted to watch american werewolf in paris or london than i would watch those movies. they took a perfectly good story and twisted it around into a copy of a story that has been told over and over again and quite frankly i'm tired of watching it. i mean hello the best part of the whole f*****g (sorry) story is she ends up with gabriel. he doesn't die. what was that about? and he's old in this movie. gabriel is supposed to be only 24 not 44 da** it. awww. and astrid who the he** came up with the idea of astrid being vivian's aunt no no no no. astrid and vivian hate each other. awwww. anyways yeah that was my little rant seriously pi**ed off. hope this helped.",
 "seriously, all these satan comes to earth movies always involve the catholics. why doesn't lucifer ever mess with the other denominations.the plot is that asmodeus (played by former jason vorhees kane hodder) has a plot to become human (but wasn't he always a demon) by getting this young girl who is his sister pregnant with his child. except maybe she isn't his sister. the plot isn't clear on this, and they inter-splice these scenes where he is seeing a shrink about his problem.the lead girl gets pregnant while still a virgin, with an incredibly creepy scene of her father giving her a gynecological exam to prove her hymen is still intact.... eeeewwwwww. her sister (played by a washed up and looking much worse for wear denise crosby) concludes that this is a sign from heaven. praise be! well, the demon baby takes mom's body for a joy ride and picks off, in order, a truck driver, her friend's boyfriend and her friend, all being watched by an ex-military priest whose mission is to kill the baby when it is born. we discover that asmodeus is actually a catholic cardinal who is running the whole thing.the ending is pretty much incomprehensible, and if you could make it that far straight through, you have a stronger stomach than i did. (i paused the film a couple of times, it was so awful.)",
 "i can't believe i'm wasting my time with a comment - but this movie is weirdly bad. if 20 different directors were brought in to film different parts of the movie without having any idea of the storyline being filmed by the other directors, this is pretty much the result i would expect.i also think some of the scenes were spliced out of order - things don't always seem to progress in order. the movie acts like we're already supposed to know about half the characters.and steve guttenberg tries to do manic, a-la-robin williams comedy in this movie. ewww. and the whole premise of putting an ex-con in charge of a bunch of kids just doesn't seem realistic in this day and age.",
 'possible spoilers --i love dennis quaid and i like meg ryan. i was looking forward to seeing them together, being married and all, i wanted to see their on-screen chemistry. okay, that being said, i guess the fact that they are actors, their off-screen relationship didn\'t have to permeate their performances, especially with this script.how stupid can a professor be to glue himself to anyone. i don\'t remember the original, but i can only assume that o\'brien probably was handcuffed to his leading lady, probably in a more inevitable way. if i were "bonded" to someone i\'d be pretty angry. the crush i would have would definitely have dissipated quickly. meg showed not even a little annoyance only slight surprise. dennis would have to take me kicking and screaming. that whole section of the movie was so horrible -- especially meg having to go to the bathroom (#2) between dumpsters in the dark at night. ewww. no f****ing way! what\'s with dennis socking every single suspect in the movie. sock first ask questions later. not once, not twice but too many times -- i could have kept count if i were so inclined. the most interesting part of the movie was nick and his family drama. too bad that couldn\'t have become more of the plot. the assumed off-screen drama leading up to this tragedy. i think it could have been written in without distracting from dex\' quest. my blame lies with the writer of this screenplay. unless the director and others doctored it up so much that it\'s unrecognizable.i won\'t even get into the real reason poor dex was murdered. how ludicrous is that. even when dex confronted the real killer and the reason was explained, (a true "film noir" moment) everyone on screen seemed bored. oh, _____ happened. oh. (yawn) "dex even says this is a silly reason for a triple murder. oh the tension, you could cut it with a spoon.if anyone but dennis had been in this movie, i\'d have to give it 1/2 star (only because i really have seen worse), but in this case 1 1/2 stars.for dennis and meg stars, see anything else.',
 "it's a kinder, gentler cyborg movie with a love story. awww. it's not as bad as it sounds. the action, when it is there, is decent and jack palance, elias koteas, and angelina jolie are always dependable. it's the fact that this is a sequel to the terrible jean claude van damme film, or is that the capper to the masters of the universe trilogy? i'm still confused about that. either way, there was really no need for this movie. what was there a need for? angelina jolie. she may play an assassin robot that can explodes mid-coitus, but, what a way to go and even though this is her first movie, she still has the presence that made her an award winner.",
 'i really wanted to like this movie, but it was just imposable. the acting was ultra hammy, the plot was annoying, and the pace was slow, sooo slowwwwww. the whole time sitting in the theater i wanted the movie to end. twenty minuets into a films and i\'m praying for an ending. sure some of the visuals were nice, but c\'mon guys, i mean really! and for a movie about a guy tuning magical instruments there really wasn\'t much music to speak of. the music there was was annoying, and boring. there were sound loud shrill sounds at times too, those were also annoying. mainly this film managed to bore me, and creep me out at the same time.i\'m glad its over. i need to go see "tideland" and wash this bad taste out of my mouth.']

In [26]:
def remove_urls(text):
    pattern = r'https?://\S+|www\S+'
    return re.sub(pattern, '', text)

In [27]:
df["clean_review"] = df["clean_review"].apply(remove_urls)

In [28]:
df["clean_review"].str.contains(
    r'https?://|www\.',
    case=False,
    regex=True
).sum()

np.int64(0)

# Step 5: Punctuation Removal

Punctuation does not usually contribute to sentiment prediction.

Removing punctuation reduces vocabulary size and improves feature quality.

In [29]:
print(string.punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [30]:
def remove_punctuation(text):
    return text.translate(
        str.maketrans(
            '',
            '',
            string.punctuation
        )
    )

In [31]:
text = "i loved this movie!!!"

remove_punctuation(text)

'i loved this movie'

In [32]:
df["clean_review"] = df["clean_review"].apply(
    remove_punctuation
)

In [33]:
print(df["review"][0][:300])

One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Tru

In [34]:
print(df["clean_review"][0][:300])

one of the other reviewers has mentioned that after watching just 1 oz episode youll be hooked they are right as this is exactly what happened with methe first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not

In [35]:
import string

punct_count = df["clean_review"].str.contains(
    f"[{string.punctuation}]",
    regex=True
).sum()

print(punct_count)

0

# Step 5 Findings

### Punctuation Removal

The following punctuation symbols were removed:

- .
- ,
- !
- ?
- :
- ;
- '
- "
- (
- )
- /
- -

### Benefits

1. Reduced vocabulary size.
2. Improved text consistency.
3. Simplified tokenization.

### Conclusion

Punctuation noise has been removed successfully.

In [36]:
print(punct_count)

0

In [37]:
df["clean_review"].str.contains(
    r"\d",
    regex=True
).sum()

np.int64(27751)

# Step 6: Number Removal

Numbers generally do not contribute significantly to sentiment classification.

Removing numbers helps reduce noise and improves text consistency.

In [38]:
def remove_numbers(text):
    return re.sub(r"\d+", "", text)

In [39]:
df["clean_review"] = df["clean_review"].apply(
    remove_numbers
)

In [40]:
df["clean_review"].str.contains(
    r"\d",
    regex=True
).sum()

np.int64(0)

In [41]:
print(df["review"][0][:300])

One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Tru

In [42]:
print(df["clean_review"][0][:300])

one of the other reviewers has mentioned that after watching just  oz episode youll be hooked they are right as this is exactly what happened with methe first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a

# Step 6 Findings

### Number Removal

Numeric values such as:

- 10
- 100
- 2007
- 3

were removed successfully.

### Benefits

1. Reduced textual noise.
2. Improved feature consistency.
3. Simplified vocabulary.

### Conclusion

Numbers have been removed from the review text.

In [43]:
type(df["clean_review"][0])

str

# Step 7: Tokenization
What is Tokenization?

Tokenization means:

Before:   
i love this movie

After:  
['i', 'love', 'this', 'movie']

These individual words are called:

Tokens

In [44]:
df["tokens"] = df["clean_review"].apply(
    lambda x: x.split()
)

In [45]:
df[
    ["clean_review", "tokens"]
].head()

,clean_review,tokens
0,one of the other reviewers has mentioned that ...,"[one, of, the, other, reviewers, has, mentione..."
1,a wonderful little production the filming tech...,"[a, wonderful, little, production, the, filmin..."
2,i thought this was a wonderful way to spend ti...,"[i, thought, this, was, a, wonderful, way, to,..."
3,basically theres a family where a little boy j...,"[basically, theres, a, family, where, a, littl..."
4,petter matteis love in the time of money is a ...,"[petter, matteis, love, in, the, time, of, mon..."

In [46]:
print(df["tokens"][0])

['one', 'of', 'the', 'other', 'reviewers', 'has', 'mentioned', 'that', 'after', 'watching', 'just', 'oz', 'episode', 'youll', 'be', 'hooked', 'they', 'are', 'right', 'as', 'this', 'is', 'exactly', 'what', 'happened', 'with', 'methe', 'first', 'thing', 'that', 'struck', 'me', 'about', 'oz', 'was', 'its', 'brutality', 'and', 'unflinching', 'scenes', 'of', 'violence', 'which', 'set', 'in', 'right', 'from', 'the', 'word', 'go', 'trust', 'me', 'this', 'is', 'not', 'a', 'show', 'for', 'the', 'faint', 'hearted', 'or', 'timid', 'this', 'show', 'pulls', 'no', 'punches', 'with', 'regards', 'to', 'drugs', 'sex', 'or', 'violence', 'its', 'is', 'hardcore', 'in', 'the', 'classic', 'use', 'of', 'the', 'wordit', 'is', 'called', 'oz', 'as', 'that', 'is', 'the', 'nickname', 'given', 'to', 'the', 'oswald', 'maximum', 'security', 'state', 'penitentary', 'it', 'focuses', 'mainly', 'on', 'emerald', 'city', 'an', 'experimental', 'section', 'of', 'the', 'prison', 'where', 'all', 'the', 'cells', 'have', 'glass', 'fronts', 'and', 'face', 'inwards', 'so', 'privacy', 'is', 'not', 'high', 'on', 'the', 'agenda', 'em', 'city', 'is', 'home', 'to', 'manyaryans', 'muslims', 'gangstas', 'latinos', 'christians', 'italians', 'irish', 'and', 'moreso', 'scuffles', 'death', 'stares', 'dodgy', 'dealings', 'and', 'shady', 'agreements', 'are', 'never', 'far', 'awayi', 'would', 'say', 'the', 'main', 'appeal', 'of', 'the', 'show', 'is', 'due', 'to', 'the', 'fact', 'that', 'it', 'goes', 'where', 'other', 'shows', 'wouldnt', 'dare', 'forget', 'pretty', 'pictures', 'painted', 'for', 'mainstream', 'audiences', 'forget', 'charm', 'forget', 'romanceoz', 'doesnt', 'mess', 'around', 'the', 'first', 'episode', 'i', 'ever', 'saw', 'struck', 'me', 'as', 'so', 'nasty', 'it', 'was', 'surreal', 'i', 'couldnt', 'say', 'i', 'was', 'ready', 'for', 'it', 'but', 'as', 'i', 'watched', 'more', 'i', 'developed', 'a', 'taste', 'for', 'oz', 'and', 'got', 'accustomed', 'to', 'the', 'high', 'levels', 'of', 'graphic', 'violence', 'not', 'just', 'violence', 'but', 'injustice', 'crooked', 'guards', 'wholl', 'be', 'sold', 'out', 'for', 'a', 'nickel', 'inmates', 'wholl', 'kill', 'on', 'order', 'and', 'get', 'away', 'with', 'it', 'well', 'mannered', 'middle', 'class', 'inmates', 'being', 'turned', 'into', 'prison', 'bitches', 'due', 'to', 'their', 'lack', 'of', 'street', 'skills', 'or', 'prison', 'experience', 'watching', 'oz', 'you', 'may', 'become', 'comfortable', 'with', 'what', 'is', 'uncomfortable', 'viewingthats', 'if', 'you', 'can', 'get', 'in', 'touch', 'with', 'your', 'darker', 'side']

In [47]:
len(df["tokens"][0])

300

In [48]:
type(df["tokens"][0])

list

# Step 7 Findings

### Tokenization

The cleaned reviews were converted into lists of words (tokens).

Example:

Before:
i love this movie

After:
['i', 'love', 'this', 'movie']

### Benefits

1. Enables stopword removal.
2. Enables lemmatization.
3. Prepares text for feature extraction.

### Conclusion

The review text has been successfully tokenized.

# Step 8: Stopword Removal (Sentiment-Aware Version)
What are Stopwords?

Stopwords are extremely common words that usually do not carry significant meaning.

Examples:

the
a
an
is
are
was
were
of
in
on
at
for
with

Example
Before
['this', 'movie', 'is', 'very', 'good']
After
['movie', 'good']

In [49]:
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [50]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

In [51]:
sentiment_words = {
    "not",
    "no",
    "nor",
    "never"
}

In [52]:
stop_words = stop_words - sentiment_words

In [53]:
print("not" in stop_words)
print("no" in stop_words)
print("nor" in stop_words)
print("never" in stop_words)

False
False
False
False

In [54]:
def remove_stopwords(tokens):
    return [
        word
        for word in tokens
        if word not in stop_words
    ]

In [55]:
df["tokens_no_stopwords"] = df["tokens"].apply(
    remove_stopwords
)

In [56]:
print(df["tokens"][0][:30])

['one', 'of', 'the', 'other', 'reviewers', 'has', 'mentioned', 'that', 'after', 'watching', 'just', 'oz', 'episode', 'youll', 'be', 'hooked', 'they', 'are', 'right', 'as', 'this', 'is', 'exactly', 'what', 'happened', 'with', 'methe', 'first', 'thing', 'that']

In [57]:
print(df["tokens_no_stopwords"][0][:30])

['one', 'reviewers', 'mentioned', 'watching', 'oz', 'episode', 'youll', 'hooked', 'right', 'exactly', 'happened', 'methe', 'first', 'thing', 'struck', 'oz', 'brutality', 'unflinching', 'scenes', 'violence', 'set', 'right', 'word', 'go', 'trust', 'not', 'show', 'faint', 'hearted', 'timid']

In [58]:
len(df["tokens"][0])

300

In [59]:
len(df["tokens_no_stopwords"][0])

171

In [60]:
test_sentence = [
    "this",
    "movie",
    "is",
    "not",
    "good"
]

remove_stopwords(test_sentence)

['movie', 'not', 'good']

# Step 8 Findings

### Stopword Removal

Common English stopwords were removed from the tokenized reviews.

Examples removed:

- the
- is
- are
- was
- of
- in
- on
- at

Important sentiment words retained:

- not
- no
- nor
- never

### Benefits

1. Reduced vocabulary size.
2. Reduced textual noise.
3. Improved sentiment preservation.

### Conclusion

Stopword removal was successfully applied while preserving important sentiment information.

In [61]:
print(df["tokens"][0][:30])
print(df["tokens_no_stopwords"][0][:30])

print(len(df["tokens"][0]))
print(len(df["tokens_no_stopwords"][0]))

['one', 'of', 'the', 'other', 'reviewers', 'has', 'mentioned', 'that', 'after', 'watching', 'just', 'oz', 'episode', 'youll', 'be', 'hooked', 'they', 'are', 'right', 'as', 'this', 'is', 'exactly', 'what', 'happened', 'with', 'methe', 'first', 'thing', 'that']
['one', 'reviewers', 'mentioned', 'watching', 'oz', 'episode', 'youll', 'hooked', 'right', 'exactly', 'happened', 'methe', 'first', 'thing', 'struck', 'oz', 'brutality', 'unflinching', 'scenes', 'violence', 'set', 'right', 'word', 'go', 'trust', 'not', 'show', 'faint', 'hearted', 'timid']
300
171

# Step 9: Lemmatization

This is the final major NLP preprocessing step.

# What is Lemmatization?

Words can appear in many forms:

run
running
runs
ran

All represent the same concept.

Lemmatization converts them to their root form (lemma).

In [63]:
import spacy

nlp = spacy.load("en_core_web_sm")

In [64]:
def lemmatize_tokens(tokens):
    text = " ".join(tokens)

    doc = nlp(text)

    return [
        token.lemma_
        for token in doc
    ]

In [65]:
df["tokens_lemmatized"] = df[
    "tokens_no_stopwords"
].apply(
    lemmatize_tokens
)

In [66]:
print(df["tokens_no_stopwords"][0][:30])

['one', 'reviewers', 'mentioned', 'watching', 'oz', 'episode', 'youll', 'hooked', 'right', 'exactly', 'happened', 'methe', 'first', 'thing', 'struck', 'oz', 'brutality', 'unflinching', 'scenes', 'violence', 'set', 'right', 'word', 'go', 'trust', 'not', 'show', 'faint', 'hearted', 'timid']

In [67]:
print(df["tokens_lemmatized"][0][:30])

['one', 'reviewer', 'mention', 'watch', 'oz', 'episode', 'you', 'll', 'hook', 'right', 'exactly', 'happen', 'methe', 'first', 'thing', 'strike', 'oz', 'brutality', 'unflinche', 'scene', 'violence', 'set', 'right', 'word', 'go', 'trust', 'not', 'show', 'faint', 'hearted']

In [68]:
type(df["tokens_lemmatized"][0])

list

In [69]:
len(df["tokens_lemmatized"][0])

177

# Step 9 Findings

### Lemmatization

Words were converted to their root forms.

Examples:

reviewers → reviewer

mentioned → mention

watching → watch

movies → movie

### Benefits

1. Reduced vocabulary size.
2. Improved semantic consistency.
3. Better feature extraction for machine learning.

### Conclusion

Lemmatization was successfully applied using spaCy.

# Step 10: Final Preprocessing Pipeline

In [70]:
df["final_text"] = df[
    "tokens_lemmatized"
].apply(
    lambda tokens: " ".join(tokens)
)

In [71]:
print(df["final_text"][0])

one reviewer mention watch oz episode you ll hook right exactly happen methe first thing strike oz brutality unflinche scene violence set right word go trust not show faint hearted timid show pull no punch regard drug sex violence hardcore classic use wordit call oz nickname give oswald maximum security state penitentary focus mainly emerald city experimental section prison cell glass front face inward privacy not high agenda em city home manyaryan muslim gangstas latinos christians italians irish moreso scuffle death stare dodgy dealing shady agreement never far awayi would say main appeal show due fact go show would not dare forget pretty picture paint mainstream audience forget charm forget romanceoz do not mess around first episode ever see strike nasty surreal could not say ready watch develop taste oz get accustomed high level graphic violence not violence injustice crook guard who ll sell nickel inmate who ll kill order get away well mannered middle class inmate turn prison bitch due lack street skill prison experience watch oz may become comfortable uncomfortable viewingthat get touch dark side

In [72]:
type(df["final_text"][0])

str

In [73]:
df[
    [
        "review",
        "clean_review",
        "final_text"
    ]
].head(1)

,review,clean_review,final_text
0,One of the other reviewers has mentioned that ...,one of the other reviewers has mentioned that ...,one reviewer mention watch oz episode you ll h...

In [74]:
df.to_csv(
    "../data/processed/imdb_preprocessed.csv",
    index=False
)

In [75]:
import os

os.path.exists(
    "../data/processed/imdb_preprocessed.csv"
)

True

# Step 10 Findings

### Final NLP Pipeline

The following preprocessing steps were applied:

1. Lowercasing
2. HTML Tag Removal
3. URL Removal
4. Punctuation Removal
5. Number Removal
6. Tokenization
7. Stopword Removal
8. Lemmatization

### Final Output

A processed text column named `final_text` was created and saved.

### Conclusion

The dataset is now ready for feature extraction using TF-IDF and machine learning models.