# Step 1: Environment Verification

In [1]:
import transformers
import datasets
import torch

print("Transformers:", transformers.__version__)
print("Datasets:", datasets.__version__)
print("Torch:", torch.__version__)

ModuleNotFoundError: No module named 'datasets'

In [ ]:
import torch

print("CUDA Available:", torch.cuda.is_available())

print("Device:",
      "GPU" if torch.cuda.is_available()
      else "CPU")

CUDA Available: False
Device: CPU

In [ ]:
import pandas as pd

df = pd.read_csv(
    "../data/processed/imdb_preprocessed.csv"
)

df.head()

,review,sentiment,clean_review,tokens,tokens_no_stopwords,tokens_lemmatized,final_text
0,One of the other reviewers has mentioned that ...,positive,one of the other reviewers has mentioned that ...,"['one', 'of', 'the', 'other', 'reviewers', 'ha...","['one', 'reviewers', 'mentioned', 'watching', ...","['one', 'reviewer', 'mention', 'watch', 'oz', ...",one reviewer mention watch oz episode you ll h...
1,A wonderful little production. <br /><br />The...,positive,a wonderful little production the filming tech...,"['a', 'wonderful', 'little', 'production', 'th...","['wonderful', 'little', 'production', 'filming...","['wonderful', 'little', 'production', 'filming...",wonderful little production filming technique ...
2,I thought this was a wonderful way to spend ti...,positive,i thought this was a wonderful way to spend ti...,"['i', 'thought', 'this', 'was', 'a', 'wonderfu...","['thought', 'wonderful', 'way', 'spend', 'time...","['think', 'wonderful', 'way', 'spend', 'time',...",think wonderful way spend time hot summer week...
3,Basically there's a family where a little boy ...,negative,basically theres a family where a little boy j...,"['basically', 'theres', 'a', 'family', 'where'...","['basically', 'theres', 'family', 'little', 'b...","['basically', 'there', 's', 'family', 'little'...",basically there s family little boy jake think...
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,petter matteis love in the time of money is a ...,"['petter', 'matteis', 'love', 'in', 'the', 'ti...","['petter', 'matteis', 'love', 'time', 'money',...","['petter', 'matteis', 'love', 'time', 'money',...",petter matteis love time money visually stunni...

In [ ]:
print(df.shape)

df.info()

df.head()

(49582, 7)
<class 'pandas.DataFrame'>
RangeIndex: 49582 entries, 0 to 49581
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   review               49582 non-null  str
 1   sentiment            49582 non-null  str
 2   clean_review         49582 non-null  str
 3   tokens               49582 non-null  str
 4   tokens_no_stopwords  49582 non-null  str
 5   tokens_lemmatized    49582 non-null  str
 6   final_text           49582 non-null  str
dtypes: str(7)
memory usage: 365.2 MB

,review,sentiment,clean_review,tokens,tokens_no_stopwords,tokens_lemmatized,final_text
0,One of the other reviewers has mentioned that ...,positive,one of the other reviewers has mentioned that ...,"['one', 'of', 'the', 'other', 'reviewers', 'ha...","['one', 'reviewers', 'mentioned', 'watching', ...","['one', 'reviewer', 'mention', 'watch', 'oz', ...",one reviewer mention watch oz episode you ll h...
1,A wonderful little production. <br /><br />The...,positive,a wonderful little production the filming tech...,"['a', 'wonderful', 'little', 'production', 'th...","['wonderful', 'little', 'production', 'filming...","['wonderful', 'little', 'production', 'filming...",wonderful little production filming technique ...
2,I thought this was a wonderful way to spend ti...,positive,i thought this was a wonderful way to spend ti...,"['i', 'thought', 'this', 'was', 'a', 'wonderfu...","['thought', 'wonderful', 'way', 'spend', 'time...","['think', 'wonderful', 'way', 'spend', 'time',...",think wonderful way spend time hot summer week...
3,Basically there's a family where a little boy ...,negative,basically theres a family where a little boy j...,"['basically', 'theres', 'a', 'family', 'where'...","['basically', 'theres', 'family', 'little', 'b...","['basically', 'there', 's', 'family', 'little'...",basically there s family little boy jake think...
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,petter matteis love in the time of money is a ...,"['petter', 'matteis', 'love', 'in', 'the', 'ti...","['petter', 'matteis', 'love', 'time', 'money',...","['petter', 'matteis', 'love', 'time', 'money',...",petter matteis love time money visually stunni...

In [ ]:
print(df["final_text"][0])

one reviewer mention watch oz episode you ll hook right exactly happen methe first thing strike oz brutality unflinche scene violence set right word go trust not show faint hearted timid show pull no punch regard drug sex violence hardcore classic use wordit call oz nickname give oswald maximum security state penitentary focus mainly emerald city experimental section prison cell glass front face inward privacy not high agenda em city home manyaryan muslim gangstas latinos christians italians irish moreso scuffle death stare dodgy dealing shady agreement never far awayi would say main appeal show due fact go show would not dare forget pretty picture paint mainstream audience forget charm forget romanceoz do not mess around first episode ever see strike nasty surreal could not say ready watch develop taste oz get accustomed high level graphic violence not violence injustice crook guard who ll sell nickel inmate who ll kill order get away well mannered middle class inmate turn prison bitch due lack street skill prison experience watch oz may become comfortable uncomfortable viewingthat get touch dark side

In [ ]:
df["label"] = df["sentiment"].map(
    {
        "negative": 0,
        "positive": 1
    }
)

df.head()

,review,sentiment,clean_review,tokens,tokens_no_stopwords,tokens_lemmatized,final_text,label
0,One of the other reviewers has mentioned that ...,positive,one of the other reviewers has mentioned that ...,"['one', 'of', 'the', 'other', 'reviewers', 'ha...","['one', 'reviewers', 'mentioned', 'watching', ...","['one', 'reviewer', 'mention', 'watch', 'oz', ...",one reviewer mention watch oz episode you ll h...,1
1,A wonderful little production. <br /><br />The...,positive,a wonderful little production the filming tech...,"['a', 'wonderful', 'little', 'production', 'th...","['wonderful', 'little', 'production', 'filming...","['wonderful', 'little', 'production', 'filming...",wonderful little production filming technique ...,1
2,I thought this was a wonderful way to spend ti...,positive,i thought this was a wonderful way to spend ti...,"['i', 'thought', 'this', 'was', 'a', 'wonderfu...","['thought', 'wonderful', 'way', 'spend', 'time...","['think', 'wonderful', 'way', 'spend', 'time',...",think wonderful way spend time hot summer week...,1
3,Basically there's a family where a little boy ...,negative,basically theres a family where a little boy j...,"['basically', 'theres', 'a', 'family', 'where'...","['basically', 'theres', 'family', 'little', 'b...","['basically', 'there', 's', 'family', 'little'...",basically there s family little boy jake think...,0
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,petter matteis love in the time of money is a ...,"['petter', 'matteis', 'love', 'in', 'the', 'ti...","['petter', 'matteis', 'love', 'time', 'money',...","['petter', 'matteis', 'love', 'time', 'money',...",petter matteis love time money visually stunni...,1

In [ ]:
df["label"].value_counts()

label
1    24884
0    24698
Name: count, dtype: int64

## Step 2: Load Dataset

In [ ]:
import pandas as pd

df = pd.read_csv(
    "../data/processed/imdb_preprocessed.csv"
)

print(df.shape)

df.head()

(49582, 7)

,review,sentiment,clean_review,tokens,tokens_no_stopwords,tokens_lemmatized,final_text
0,One of the other reviewers has mentioned that ...,positive,one of the other reviewers has mentioned that ...,"['one', 'of', 'the', 'other', 'reviewers', 'ha...","['one', 'reviewers', 'mentioned', 'watching', ...","['one', 'reviewer', 'mention', 'watch', 'oz', ...",one reviewer mention watch oz episode you ll h...
1,A wonderful little production. <br /><br />The...,positive,a wonderful little production the filming tech...,"['a', 'wonderful', 'little', 'production', 'th...","['wonderful', 'little', 'production', 'filming...","['wonderful', 'little', 'production', 'filming...",wonderful little production filming technique ...
2,I thought this was a wonderful way to spend ti...,positive,i thought this was a wonderful way to spend ti...,"['i', 'thought', 'this', 'was', 'a', 'wonderfu...","['thought', 'wonderful', 'way', 'spend', 'time...","['think', 'wonderful', 'way', 'spend', 'time',...",think wonderful way spend time hot summer week...
3,Basically there's a family where a little boy ...,negative,basically theres a family where a little boy j...,"['basically', 'theres', 'a', 'family', 'where'...","['basically', 'theres', 'family', 'little', 'b...","['basically', 'there', 's', 'family', 'little'...",basically there s family little boy jake think...
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,petter matteis love in the time of money is a ...,"['petter', 'matteis', 'love', 'in', 'the', 'ti...","['petter', 'matteis', 'love', 'time', 'money',...","['petter', 'matteis', 'love', 'time', 'money',...",petter matteis love time money visually stunni...

In [ ]:
df.columns.tolist()

['review',
 'sentiment',
 'clean_review',
 'tokens',
 'tokens_no_stopwords',
 'tokens_lemmatized',
 'final_text']

In [ ]:
df.isnull().sum()

review                 0
sentiment              0
clean_review           0
tokens                 0
tokens_no_stopwords    0
tokens_lemmatized      0
final_text             0
dtype: int64

In [ ]:
print(df["clean_review"][0][:500])

one of the other reviewers has mentioned that after watching just  oz episode youll be hooked they are right as this is exactly what happened with methe first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the wordit is called oz as that is the nickname given to the

In [ ]:
print("FINAL_TEXT:")
print(df["final_text"][0][:300])

print("\n")

print("CLEAN_REVIEW:")
print(df["clean_review"][0][:300])

FINAL_TEXT:
one reviewer mention watch oz episode you ll hook right exactly happen methe first thing strike oz brutality unflinche scene violence set right word go trust not show faint hearted timid show pull no punch regard drug sex violence hardcore classic use wordit call oz nickname give oswald maximum secu


CLEAN_REVIEW:
one of the other reviewers has mentioned that after watching just  oz episode youll be hooked they are right as this is exactly what happened with methe first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a

# Step 3: Label Encoding

In [ ]:
df["sentiment"]

0        positive
1        positive
2        positive
3        negative
4        positive
           ...
49577    positive
49578    negative
49579    negative
49580    negative
49581    negative
Name: sentiment, Length: 49582, dtype: str

In [ ]:
df["label"] = df["sentiment"].map(
    {
        "negative": 0,
        "positive": 1
    }
)

In [ ]:
df[
    ["sentiment", "label"]
].head(10)

  sentiment  label
0  positive      1
1  positive      1
2  positive      1
3  negative      0
4  positive      1
5  positive      1
6  positive      1
7  negative      0
8  negative      0
9  positive      1

In [ ]:
df["label"].value_counts()

label
1    24884
0    24698
Name: count, dtype: int64

In [ ]:
print(
    df[
        ["sentiment", "label"]
    ].sample(10)
)

      sentiment  label
27696  negative      0
32892  negative      0
32540  positive      1
15118  negative      0
4062   positive      1
18885  positive      1
14983  negative      0
42036  positive      1
32925  negative      0
41814  negative      0

In [ ]:
print(df["label"].dtype)

int64

## Step 4: Train-Test Split

In [ ]:
X = df["clean_review"]

y = df["label"]

In [ ]:
X = df["clean_review"]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)

print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (39665,)
X_test : (9917,)
y_train: (39665,)
y_test : (9917,)

In [ ]:
print(y_train.value_counts())

print("\n")

print(y_test.value_counts())

label
1    19907
0    19758
Name: count, dtype: int64


label
1    4977
0    4940
Name: count, dtype: int64

In [ ]:
print(X_train.iloc[0][:500])

i am one of jehovahs witnesses and i also work in an acute care medical facility over the years i have seen people die from hemolytic reactions to blood transfusions have attended numerous conferences on blood born pathogens and have seen several patients become seriously ill from pathogens induced by transfused blood i have also heard several jehovahs witnesses being told that they will die if they refuse blood and after  years in the field i have never actually seen it happen leaving the quest

In [ ]:
print(type(X_train))
print(type(y_train))

<class 'pandas.Series'>
<class 'pandas.Series'>

# Step 5: Tokenization

In [ ]:
from transformers import AutoTokenizer

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(
    "distilbert-base-uncased"
)

In [ ]:
print(type(tokenizer))

<class 'transformers.models.bert.tokenization_bert.BertTokenizer'>

In [ ]:
sample_text = X_train.iloc[0]

encoded = tokenizer(
    sample_text,
    truncation=True,
    padding="max_length",
    max_length=256
)

print(encoded.keys())

KeysView({'input_ids': [101, 1045, 2572, 2028, 1997, 15333, 6806, 21927, 2015, 9390, 1998, 1045, 2036, 2147, 1999, 2019, 11325, 2729, 2966, 4322, 2058, 1996, 2086, 1045, 2031, 2464, 2111, 3280, 2013, 19610, 4747, 21252, 9597, 2000, 2668, 9099, 20523, 2015, 2031, 3230, 3365, 9281, 2006, 2668, 2141, 26835, 2015, 1998, 2031, 2464, 2195, 5022, 2468, 5667, 5665, 2013, 26835, 2015, 10572, 2011, 9099, 25608, 2098, 2668, 1045, 2031, 2036, 2657, 2195, 15333, 6806, 21927, 2015, 9390, 2108, 2409, 2008, 2027, 2097, 3280, 2065, 2027, 10214, 2668, 1998, 2044, 2086, 1999, 1996, 2492, 1045, 2031, 2196, 2941, 2464, 2009, 4148, 2975, 1996, 3160, 2003, 2009, 2428, 29205, 2000, 10214, 2668, 9099, 20523, 2015, 2030, 2003, 1996, 2451, 2012, 2312, 5770, 2075, 2013, 1996, 2645, 2006, 2023, 3277, 1996, 3277, 2005, 15333, 6806, 21927, 2015, 9390, 2003, 1037, 7191, 2028, 2017, 2442, 14689, 18249, 2013, 2668, 2003, 2025, 2019, 20080, 4861, 4067, 2017, 2005, 2023, 3185, 1998, 4352, 7928, 2006, 2009, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]})

In [ ]:
print(encoded["input_ids"][:30])

[101, 1045, 2572, 2028, 1997, 15333, 6806, 21927, 2015, 9390, 1998, 1045, 2036, 2147, 1999, 2019, 11325, 2729, 2966, 4322, 2058, 1996, 2086, 1045, 2031, 2464, 2111, 3280, 2013, 19610]

In [ ]:
print(encoded["attention_mask"][:30])

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [ ]:
print(len(encoded["input_ids"]))
print(len(encoded["attention_mask"]))

256
256

# Step 6: HuggingFace Dataset Creation

In [ ]:
from datasets import Dataset

In [ ]:
import pandas as pd

train_df = pd.DataFrame({
    "text": X_train,
    "label": y_train
})

train_df.head()

                                                    text  label
34595  i am one of jehovahs witnesses and i also work...      1
17243  amongst the standard one liner type action fil...      1
9409   realty television crew are assigned to cover a...      0
21903  the funniest scene of this movie is probably w...      0
10820  there have been far too few mainstream films s...      1

In [ ]:
print(train_df.shape)

train_df.head()

(39665, 2)

                                                    text  label
34595  i am one of jehovahs witnesses and i also work...      1
17243  amongst the standard one liner type action fil...      1
9409   realty television crew are assigned to cover a...      0
21903  the funniest scene of this movie is probably w...      0
10820  there have been far too few mainstream films s...      1

In [ ]:
test_df = pd.DataFrame({
    "text": X_test,
    "label": y_test
})

test_df.head()

                                                    text  label
34940  my wife and i watched this after dvring it off...      0
18431  i was surprised how much i enjoyed this sure i...      1
4085   such a delightful movie very heart warming one...      1
28000  la lupa mannara aka werewolf woman of  is a fi...      0
3733   first this movie was not that badit was entert...      0

In [ ]:
print(test_df.shape)

(9917, 2)

In [ ]:
train_dataset = Dataset.from_pandas(
    train_df
)

test_dataset = Dataset.from_pandas(
    test_df
)

In [ ]:
print(type(train_dataset))
print(type(test_dataset))

<class 'datasets.arrow_dataset.Dataset'>
<class 'datasets.arrow_dataset.Dataset'>

In [ ]:
train_dataset

Dataset({
    features: ['text', 'label', '__index_level_0__'],
    num_rows: 39665
})

In [ ]:
train_dataset[0]

{'text': 'i am one of jehovahs witnesses and i also work in an acute care medical facility over the years i have seen people die from hemolytic reactions to blood transfusions have attended numerous conferences on blood born pathogens and have seen several patients become seriously ill from pathogens induced by transfused blood i have also heard several jehovahs witnesses being told that they will die if they refuse blood and after  years in the field i have never actually seen it happen leaving the question is it really unreasonable to refuse blood transfusions or is the community at large benefiting from the battle on this issue the issue for jehovahs witnesses is a moral one you must abstain from blood is not an ambiguous statement thank you for this movie and allowing comments on it',
 'label': 1,
 '__index_level_0__': 34595}

In [ ]:
def tokenize_function(example):

    return tokenizer(
        example["text"],
        truncation=True,
        padding="max_length",
        max_length=256
    )

In [ ]:
train_dataset = train_dataset.map(
    tokenize_function,
    batched=True
)

test_dataset = test_dataset.map(
    tokenize_function,
    batched=True
)

Map:   0%|          | 0/39665 [00:00<?, ? examples/s]

Map:   0%|          | 0/9917 [00:00<?, ? examples/s]

In [ ]:
train_dataset

Dataset({
    features: ['text', 'label', '__index_level_0__', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 39665
})

In [ ]:
train_dataset[0]

{'text': 'i am one of jehovahs witnesses and i also work in an acute care medical facility over the years i have seen people die from hemolytic reactions to blood transfusions have attended numerous conferences on blood born pathogens and have seen several patients become seriously ill from pathogens induced by transfused blood i have also heard several jehovahs witnesses being told that they will die if they refuse blood and after  years in the field i have never actually seen it happen leaving the question is it really unreasonable to refuse blood transfusions or is the community at large benefiting from the battle on this issue the issue for jehovahs witnesses is a moral one you must abstain from blood is not an ambiguous statement thank you for this movie and allowing comments on it',
 'label': 1,
 '__index_level_0__': 34595,
 'input_ids': [101,
  1045,
  2572,
  2028,
  1997,
  15333,
  6806,
  21927,
  2015,
  9390,
  1998,
  1045,
  2036,
  2147,
  1999,
  2019,
  11325,
  2729,
  2966,
  4322,
  2058,
  1996,
  2086,
  1045,
  2031,
  2464,
  2111,
  3280,
  2013,
  19610,
  4747,
  21252,
  9597,
  2000,
  2668,
  9099,
  20523,
  2015,
  2031,
  3230,
  3365,
  9281,
  2006,
  2668,
  2141,
  26835,
  2015,
  1998,
  2031,
  2464,
  2195,
  5022,
  2468,
  5667,
  5665,
  2013,
  26835,
  2015,
  10572,
  2011,
  9099,
  25608,
  2098,
  2668,
  1045,
  2031,
  2036,
  2657,
  2195,
  15333,
  6806,
  21927,
  2015,
  9390,
  2108,
  2409,
  2008,
  2027,
  2097,
  3280,
  2065,
  2027,
  10214,
  2668,
  1998,
  2044,
  2086,
  1999,
  1996,
  2492,
  1045,
  2031,
  2196,
  2941,
  2464,
  2009,
  4148,
  2975,
  1996,
  3160,
  2003,
  2009,
  2428,
  29205,
  2000,
  10214,
  2668,
  9099,
  20523,
  2015,
  2030,
  2003,
  1996,
  2451,
  2012,
  2312,
  5770,
  2075,
  2013,
  1996,
  2645,
  2006,
  2023,
  3277,
  1996,
  3277,
  2005,
  15333,
  6806,
  21927,
  2015,
  9390,
  2003,
  1037,
  7191,
  2028,
  2017,
  2442,
  14689,
  18249,
  2013,
  2668,
  2003,
  2025,
  2019,
  20080,
  4861,
  4067,
  2017,
  2005,
  2023,
  3185,
  1998,
  4352,
  7928,
  2006,
  2009,
  102,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'token_type_ids': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'attention_mask': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0]}

# Step 7: Load DistilBERT Model

In [ ]:
from transformers import AutoModelForSequenceClassification

In [ ]:
model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
print(type(model))

<class 'transformers.models.distilbert.modeling_distilbert.DistilBertForSequenceClassification'>

In [ ]:
print(model.config.num_labels)

2

In [ ]:
import torch

device = (
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

print(device)

cpu

In [ ]:
model.to(device)

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [ ]:
print(model)

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

# Step 8: Training Arguments

In [ ]:
from transformers import (
    TrainingArguments,
    Trainer
)

In [ ]:
training_args = TrainingArguments(
    output_dir="../models/distilbert_output",

    eval_strategy="epoch",

    save_strategy="epoch",

    num_train_epochs=1,

    per_device_train_batch_size=8,

    per_device_eval_batch_size=8,

    logging_dir="../reports/logs",

    logging_steps=100,

    load_best_model_at_end=True,

    report_to="none"
)

[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

In [ ]:
print(training_args)

TrainingArguments(
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_static_graph=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
enable_jit_checkpoint=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_full_eval=False,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_num_input_tokens_seen=no,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=-1,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=../reports/logs,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=100,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs=None,
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
neftune_noise_alpha=None,
num_train_epochs=1,
optim=OptimizerNames.ADAMW_TORCH_FUSED,
optim_args=None,
optim_target_modules=None,
output_dir=../models/distilbert_output,
parallelism_config=None,
per_device_eval_batch_size=8,
per_device_train_batch_size=8,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
trackio_bucket_id=None,
trackio_space_id=None,
trackio_static_space_id=None,
train_sampling_strategy=random,
use_cache=False,
use_cpu=False,
use_liger_kernel=False,
warmup_ratio=None,
warmup_steps=0,
weight_decay=0.0,
)

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support
)

import numpy as np

In [ ]:
def compute_metrics(eval_pred):

    logits, labels = eval_pred

    predictions = np.argmax(
        logits,
        axis=1
    )

    precision, recall, f1, _ = (
        precision_recall_fscore_support(
            labels,
            predictions,
            average="binary"
        )
    )

    accuracy = accuracy_score(
        labels,
        predictions
    )

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

In [ ]:
compute_metrics

# Step 9: Fine-Tuning DistilBERT

In [ ]:
trainer = Trainer(
    model=model,

    args=training_args,

    train_dataset=train_dataset,

    eval_dataset=test_dataset,

    compute_metrics=compute_metrics
)

In [ ]:
type(trainer)

transformers.trainer.Trainer

In [ ]:
trainer.train()

d:\Sentiment_Analysis_Project\venv\Lib\site-packages\torch\utils\data\dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

KeyboardInterrupt:

# Step 10: Evaluation

In [ ]:
bert_results = trainer.evaluate()

bert_results

{'eval_loss': 0.43435239791870117,
 'eval_accuracy': 0.8077039427246143,
 'eval_precision': 0.8812717337307501,
 'eval_recall': 0.7128792445248141,
 'eval_f1': 0.788181717205376}

In [ ]:

bert_accuracy = bert_results["eval_accuracy"]
bert_precision = bert_results["eval_precision"]
bert_recall = bert_results["eval_recall"]
bert_f1 = bert_results["eval_f1"]

print("Accuracy :", bert_accuracy)
print("Precision:", bert_precision)
print("Recall   :", bert_recall)
print("F1 Score :", bert_f1)

Accuracy : 0.8077039427246143
Precision: 0.8812717337307501
Recall   : 0.7128792445248141
F1 Score : 0.788181717205376

In [ ]:
print(X_train.iloc[0])

i am one of jehovahs witnesses and i also work in an acute care medical facility over the years i have seen people die from hemolytic reactions to blood transfusions have attended numerous conferences on blood born pathogens and have seen several patients become seriously ill from pathogens induced by transfused blood i have also heard several jehovahs witnesses being told that they will die if they refuse blood and after  years in the field i have never actually seen it happen leaving the question is it really unreasonable to refuse blood transfusions or is the community at large benefiting from the battle on this issue the issue for jehovahs witnesses is a moral one you must abstain from blood is not an ambiguous statement thank you for this movie and allowing comments on it

In [ ]:
import os

print(os.listdir("../models/distilbert_output"))
print()
print(os.listdir("../models/distilbert_sentiment_model"))

['checkpoint-4959']

['config.json', 'model.safetensors', 'special_tokens_map.json', 'tokenizer.json', 'tokenizer_config.json']

In [ ]:
import json

with open(
    "../models/distilbert_sentiment_model/config.json",
    "r",
    encoding="utf-8"
) as f:
    print(f.read()[:1000])

In [ ]:
import os

print(
    os.path.getsize(
        "../models/distilbert_sentiment_model/config.json"
    )
)

0

In [ ]:
import os

print(
    os.listdir(
        "../models/distilbert_output/checkpoint-4959"
    )
)

['config.json', 'model.safetensors', 'optimizer.pt', 'rng_state.pth', 'scheduler.pt', 'trainer_state.json', 'training_args.bin']

In [ ]:
with open(
    "../models/distilbert_output/checkpoint-4959/config.json",
    "r",
    encoding="utf-8"
) as f:
    print(f.read()[:1000])

{
  "activation": "gelu",
  "architectures": [
    "DistilBertForSequenceClassification"
  ],
  "attention_dropout": 0.1,
  "bos_token_id": null,
  "dim": 768,
  "dropout": 0.1,
  "dtype": "float32",
  "eos_token_id": null,
  "hidden_dim": 3072,
  "initializer_range": 0.02,
  "max_position_embeddings": 512,
  "model_type": "distilbert",
  "n_heads": 12,
  "n_layers": 6,
  "pad_token_id": 0,
  "problem_type": "single_label_classification",
  "qa_dropout": 0.1,
  "seq_classif_dropout": 0.2,
  "sinusoidal_pos_embds": false,
  "tie_weights_": true,
  "tie_word_embeddings": true,
  "transformers_version": "5.9.0",
  "use_cache": false,
  "vocab_size": 30522
}

In [ ]:
from transformers import AutoModelForSequenceClassification

checkpoint_model = AutoModelForSequenceClassification.from_pretrained(
    "../models/distilbert_output/checkpoint-4959"
)

print(type(checkpoint_model))
print(checkpoint_model.config.num_labels)

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

<class 'transformers.models.distilbert.modeling_distilbert.DistilBertForSequenceClassification'>
2

In [ ]:
trainer.model = checkpoint_model

checkpoint_results = trainer.evaluate()

checkpoint_results

d:\Sentiment_Analysis_Project\venv\Lib\site-packages\torch\utils\data\dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

{'eval_loss': 0.24931782484054565,
 'eval_accuracy': 0.9145911061813048,
 'eval_precision': 0.9198861325742171,
 'eval_recall': 0.9089813140446051,
 'eval_f1': 0.9144012127337039}

In [ ]:
checkpoint_results

{'eval_loss': 0.24931782484054565,
 'eval_accuracy': 0.9145911061813048,
 'eval_precision': 0.9198861325742171,
 'eval_recall': 0.9089813140446051,
 'eval_f1': 0.9144012127337039}

# Step 11: Model Comparison

In [ ]:
import pandas as pd

comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "SVM",
        "DistilBERT"
    ],

    "Accuracy": [
        0.8921,
        0.8869,
        0.9146
    ],

    "Precision": [
        0.8851,
        0.8868,
        0.9199
    ],

    "Recall": [
        0.9021,
        0.8879,
        0.9090
    ],

    "F1 Score": [
        0.8935,
        0.8873,
        0.9144
    ]
})

comparison

                 Model  Accuracy  Precision  Recall  F1 Score
0  Logistic Regression    0.8921     0.8851  0.9021    0.8935
1                  SVM    0.8869     0.8868  0.8879    0.8873
2           DistilBERT    0.9146     0.9199  0.9090    0.9144

# Step 12: Save Final DistilBERT Properly

In [ ]:
final_model_path = "../models/distilbert_final"

checkpoint_model.save_pretrained(
    final_model_path
)

tokenizer.save_pretrained(
    final_model_path
)

print("Final DistilBERT Saved Successfully")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Final DistilBERT Saved Successfully

In [ ]:
import os

print(
    os.listdir(
        "../models/distilbert_final"
    )
)

['config.json', 'model.safetensors', 'tokenizer.json', 'tokenizer_config.json']

In [ ]:
print(train_dataset[0]["label"])
print(train_dataset[0]["text"][:300])